import { Inter, Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
import { BasketProvider } from "@/context/basketContext";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} min-h-screen  flex flex-col justify-between`}
      >
        <BasketProvider>
          <Navbar />
          <div className="flex-1">{children}</div>
          <Footer />
        </BasketProvider>
      </body>
    </html>
  );
}
